name: mongo-sharding-replicated-redis
services:
  # Кеширование
  redis:
    image: dh-mirror.gitverse.ru/redis:latest
    container_name: redis
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.15
    ports:
      - 6379:6379

  # Сервер конфигурации
  configsvr:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configsvr
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    command: mongod --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    volumes:
      - configsvr_data:/data/db

  # Шард 1: Реплика-сет
  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    command: mongod --shardsvr --replSet shard1RS --port 27017 --bind_ip_all
    volumes:
      - shard1-1_data:/data/db

  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    command: mongod --shardsvr --replSet shard1RS --port 27017 --bind_ip_all
    volumes:
      - shard1-2_data:/data/db

  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-3
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    command: mongod --shardsvr --replSet shard1RS --port 27017 --bind_ip_all
    volumes:
      - shard1-3_data:/data/db

  # Шард 2: Реплика-сет
  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    command: mongod --shardsvr --replSet shard2RS --port 27017 --bind_ip_all
    volumes:
      - shard2-1_data:/data/db

  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.13
    command: mongod --shardsvr --replSet shard2RS --port 27017 --bind_ip_all
    volumes:
      - shard2-2_data:/data/db

  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-3
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.14
    command: mongod --shardsvr --replSet shard2RS --port 27017 --bind_ip_all
    volumes:
      - shard2-3_data:/data/db

  # Роутер
  mongos_router:
    container_name: mongos_router
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command: mongos --configdb configReplSet/configsvr:27017 --bind_ip_all --port 27017
    depends_on:
      - configsvr
    ports:
      - 27017:27017

  # Приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
      - redis
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    networks:
      app-network:
        ipv4_address: 173.17.0.2

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  configsvr_data:
  shard1-1_data:
  shard1-2_data:
  shard1-3_data:
  shard2-1_data:
  shard2-2_data:
  shard2-3_data: